WIP

diff --git a/.github/workflows/edr-npm-release.yml b/.github/workflows/edr-npm-release.yml
--- a/.github/workflows/edr-npm-release.yml
+++ b/.github/workflows/edr-npm-release.yml
@@ -116,19 +116,6 @@ jobs:
         if: ${{ !matrix.settings.docker }}
         run: pnpm install --frozen-lockfile --prefer-offline
 
-      # Have to clean up older Node version / symlinks to be able to install newer version
-      # TODO: Consider creating docker images with Node 20 and Rust pre-installed. 
-      - name: Nuke node / npm / corepack installs for Docker
-        uses: addnab/docker-run-action@v3
-        if: ${{ matrix.settings.docker }}
-        with:
-          image: ${{ matrix.settings.docker }}
-          options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build/crates/edr_napi"
-          run: |
-            set -e
-            corepack disable
-            rm -f /usr/local/bin/{node,npm,npx,corepack,pnpm,pnpx} || true
-
       - name: Build in docker (x86_64-unknown-linux-gnu)
         uses: addnab/docker-run-action@v3
         if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
@@ -158,6 +145,11 @@ jobs:
           options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build/crates/edr_napi"
           run: |
             set -e
+            # Have to clean up older Node version / symlinks to be able to install newer version
+            # TODO: Consider creating docker images with Node 20 and Rust pre-installed. 
+            corepack disable
+            rm -f /usr/local/bin/{node,npm,npx,corepack,pnpm,pnpx} || true
+
             rustup target add aarch64-unknown-linux-gnu
 
             npm i -g pnpm@10.17.1
@@ -174,6 +166,11 @@ jobs:
           options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build/crates/edr_napi"
           run: |
             set -e
+            # Have to clean up older Node version / symlinks to be able to install newer version
+            # TODO: Consider creating docker images with Node 20 and Rust pre-installed. 
+            corepack disable
+            rm -f /usr/local/bin/{node,npm,npx,corepack,pnpm,pnpx} || true
+
             apk add --no-cache curl ca-certificates perl
 
             # get package manager n at point it at a musl-capable mirror
